resources:
  - add_safe_to_evict/add_safe_to_evict.yaml
  - check_deprecated_apis.yaml
  - disallow-empty-ingress-host/disallow_empty_ingress_host.yaml


patches:
  - patch: |-
      - op: replace
        path: /spec/failurePolicy
        value: Ignore
    target:
      kind: ClusterPolicy
