resources:
  - add_safe_to_evict/add_safe_to_evict.yaml
  - check_deprecated_apis.yaml
  - disallow-empty-ingress-host/disallow_empty_ingress_host.yaml
  - disallow_cri_sock_mount/disallow_cri_sock_mount.yaml
  - disallow_default_namespace/disallow_default_namespace.yaml
  - disallow_helm_tiller/disallow_helm_tiller.yaml
  - disallow_latest_tag/disallow_latest_tag.yaml


patches:
  - patch: |-
      - op: replace
        path: /spec/failurePolicy
        value: Ignore
    target:
      kind: ClusterPolicy
